sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost1.55-dev
            - libboost-system1.55-dev
            - libboost-date-time1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-program-options1.55-dev
      env: COMPILER=g++-7
    - compiler: clang
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libboost1.55-dev
            - libboost-system1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-date-time1.55-dev
            - libboost-program-options1.55-dev
      env: COMPILER=clang++-3.8

before_install:
  - sudo apt-get update -qq
install:
  - curl https://cmake.org/files/v3.8/cmake-3.8.1-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. -B. -H..  && make
notifications:
  email:
    recipients:
      - corenting@gmail.com
