sudo: required
dist: trusty
language: cpp
addons:
  apt:
    sources:
      - boost-latest
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - libboost1.55-dev
      - libboost-program-options1.55-dev
compiler:
  - clang
  - gcc
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - curl https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC -B. -H.. && make
notifications:
  email:
    recipients:
      - corenting@gmail.com
