sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake3
            - g++-6
            - libboost1.55-dev
            - libboost-system1.55-dev
            - libboost-date-time1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-program-options1.55-dev
      env: COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake3
            - clang-3.9
            - libboost1.55-dev
            - libboost-system1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-date-time1.55-dev
            - libboost-program-options1.55-dev
      env: COMPILER=clang++-3.9

before_install:
  - sudo apt-get update -qq
  - git submodule update --init --recursive
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. -B. -H..  && make
notifications:
  email:
    recipients:
      - corenting@gmail.com
