dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - libboost1.55-dev
      - libboost-system1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-date-time1.55-dev
      - libboost-program-options1.55-dev
script:
  # Link gcc-6 and g++-6 to their standard commands
  - ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - ln -s /usr/bin/g++-7 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - mkdir build
  - cd build
  - cmake .. && make
notifications:
  email:
    recipients:
      - corenting@gmail.com